name: Executing_multiple_job

on: push

jobs:
  buld_job:
    runs-on: ubuntu-latest
    steps:
      - name: install cowsay
        run: sudo apt-get install cowsay -y
      - name: execut cowsay cmd
        run: cowsay -f dragon "Welcome to GitHub Actions! chinna" >> dragon.txt
      
      - name: upload the dragon.txt file as an artifact
        uses: actions/upload-artifact@v5
        with:
          name: dragon-artifact
          path: dragon.txt

  test_job:
      needs: buld_job
      runs-on: ubuntu-latest
      steps:
        - name: download the artifact
          uses: actions/download-artifact@v5
          with:
            name: dragon-artifact
        - name: Test file content
          run: grep -i "chinna" dragon.txt
    

  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: download the artifact
        uses: actions/download-artifact@v5
        with:
          name: dragon-artifact
      - name: Read file
        run: cat dragon.txt
      - name: Deploy step
        run: echo "Deploying the application..."