name: My first workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:

      - name: checkout the repository
        uses: actions/checkout@v6
      - name: read the README file
        run: |
             cat README.md
             ls -ltra
             echo " Hello chinna!"
      - name: Gerate ASCII art
        run: |
             cowsay -f dragon "Welcome to GitHub Actions!" >> dragon.txt
             