name: variable and secrets
on: 
    #schedule:
     #- cron: '0 0 * * *' # This will run the workflow every
    push
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: docker build -t docker.io/dockerusername/imageName:latest 
            - name: Docker login
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  